### PR TITLE
Use ck86/gulp-bower-files to concat the bower components & remove grunt.

### LINKED ISSUE #8: Bower components and CSS imports
How should one integrate bower_components css files into the workflow? I'm pretty sure manual isn't the right way to go :)

### PR DESCRIPTION
**Pull request by jdachtera**
This PR also fixes #8 and #9.

### CODE REVIEW

**Comment by aamirshah** [comment]
This is simply AWESOME :+1: , but there is one issue, in case I use this bower.json file

```
{
  "name": "aamir-shah",
  "version": "0.0.0",
  "dependencies": {
    "angular": "1.2.6",
    "angular-resource": "1.2.6",
    "angular-cookies": "1.2.6",
    "angular-sanitize": "1.2.6",
    "angular-route": "1.2.6",
    "angular-animate": "1.2.6",

    "bootstrap": "*",
    "jquery": "~2.1.1"

  },
  "devDependencies": {
    "angular-mocks": "1.2.6",
    "angular-scenario": "1.2.6"
  },
  "overrides": {
    "angular-resource": {
      "dependencies": "angular"
    },
    "angular-cookies": {
      "dependencies": "angular"
    },
    "angular-sanitize": {
      "dependencies": "angular"
    },
    "angular-route": {
      "dependencies": "angular"
    },
    "angular-animate": {
      "dependencies": "angular"
    },
    "bootstrap": {
      "dependencies": "jquery"
    }
  }
}

```

It will throw an error on console that `Bootstrap's JavaScript requires jQuery`. But in the `dependencies` if I place `jquery` before the `bootstrap` then everything works fine. My questions is if that is the case what is the use of `overrides` ?

**Comment by jdachtera** [comment]
With the overrides property you can override the values of the components bower.json. E.g. angular-animate's bower.json contains:

```
{
  "name": "angular-animate",
  "version": "1.2.6",
  "main": "./angular-animate.js",
  "dependencies": {
    "angular": "1.2.6"
  }
}
```

Now with "overrides" you could override the "main" and "dependencies" property. But you only need to do that, if the component does not correctly specify its dependencies or main files (or you don't want specific files). In our case all the components (angular,  bootstrap, etc.) all have proper bower.json files. So we don't even need to override anything.

I'm not sure why it behaves like you describe but maybe the format is wrong. Instead of 

```
"dependencies": "jquery"
```

it should probably read like that:

```
"dependencies": {
   "jquery": "*"
}
```

But anyway as I said we don't need it, because bootstrap already defines it dependencies properly:

```
{
  "name": "bootstrap",
  "version": "3.1.1",
  "main": [
    "./dist/css/bootstrap.css",
    "./dist/js/bootstrap.js",
    "./dist/fonts/glyphicons-halflings-regular.eot",
    "./dist/fonts/glyphicons-halflings-regular.svg",
    "./dist/fonts/glyphicons-halflings-regular.ttf",
    "./dist/fonts/glyphicons-halflings-regular.woff"
  ],
  "ignore": [
    "**/.*",
    "_config.yml",
    "CNAME",
    "composer.json",
    "CONTRIBUTING.md",
    "docs",
    "js/tests"
  ],
  "dependencies": {
    "jquery": ">= 1.9.0"
  }
}
```

Please again take a look at my additional changes. I removed the overrides and at least on my machine all dependencies get resolved nicely. I also added a hook to copy the assets of bower_components e.g. bootstrap's fonts and included a hint on how to use this with bootstrap-sass-official.

**Comment by gaboesquivel** [comment]
@jdachtera :+1:

**Comment by aamirshah** [comment]
@jdachtera :+1:

**Pull request merged**
